# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Drew Heavner
tagline:          'Taking life one line at a time'
description:      'The ramblings of a passionate Android developer trying to make his mark on this world.'
url:              http://r0adkll.github.io
baseurl:          /

author:
  name:           'Drew Heavner'
  url:            https://twitter.com/R0ADKLL

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/r0adkll
